"""Additive v9 file metadata, place links and durable collection attempts."""


def migrate_attachments(c):
    c.execute("""
        CREATE TABLE IF NOT EXISTS pongdang_data.attachment (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          provider text NOT NULL,
          source_record_id text NOT NULL,
          evidence_hash text NOT NULL,
          sha256 text NOT NULL CHECK(sha256 ~ '^[0-9a-f]{64}$'),
          storage_key text NOT NULL,
          media_type text NOT NULL CHECK(media_type IN
            ('image/jpeg','image/png','image/webp')),
          byte_size bigint NOT NULL CHECK(byte_size>0),
          name text NOT NULL,
          source_url text NOT NULL,
          original_url text NOT NULL,
          license text NOT NULL CHECK(license IN ('Type1','Type3')),
          attribution text NOT NULL,
          source_modified_at timestamptz,
          fetched_at timestamptz NOT NULL,
          status text NOT NULL CHECK(status IN ('active','superseded')),
          UNIQUE(provider,source_record_id,evidence_hash))
    """)
    c.execute("""
        CREATE UNIQUE INDEX IF NOT EXISTS attachment_active_source
        ON pongdang_data.attachment(provider,source_record_id) WHERE status='active'
    """)
    c.execute("""
        CREATE TABLE IF NOT EXISTS pongdang_data.place_attachment (
          spot_id bigint PRIMARY KEY REFERENCES pongdang_data.spots_waterspot(id),
          attachment_id bigint NOT NULL REFERENCES pongdang_data.attachment(id),
          match_method text NOT NULL CHECK(match_method IN
            ('provider_id','name_and_coordinates')),
          linked_at timestamptz NOT NULL)
    """)
    c.execute("""
        CREATE INDEX IF NOT EXISTS place_attachment_file
        ON pongdang_data.place_attachment(attachment_id)
    """)
    c.execute("""
        CREATE TABLE IF NOT EXISTS pongdang_data.attachment_collection (
          spot_id bigint PRIMARY KEY REFERENCES pongdang_data.spots_waterspot(id),
          state text NOT NULL CHECK(state IN ('available','no_image','no_match',
            'ambiguous','restricted','failed')),
          checked_at timestamptz NOT NULL,
          last_success_at timestamptz,
          next_attempt_at timestamptz NOT NULL,
          consecutive_failures integer NOT NULL DEFAULT 0,
          error_code text NOT NULL DEFAULT '')
    """)
    for table in ("attachment", "place_attachment", "attachment_collection"):
        c.execute(f"REVOKE ALL ON pongdang_data.{table} FROM PUBLIC")
    c.execute("UPDATE pongdang_data.schema_version SET version=9 WHERE id=1")


def migrate_photo_detail_cache(c):
    """Photos follow stored detail revisions instead of a recurring provider read."""
    c.execute(
        "ALTER TABLE pongdang_data.attachment_collection "
        "ALTER COLUMN next_attempt_at DROP NOT NULL"
    )
    c.execute(
        "ALTER TABLE pongdang_data.attachment_collection "
        "ADD COLUMN IF NOT EXISTS source_detail_id bigint "
        "REFERENCES pongdang_data.place_detail(id)"
    )
    c.execute(
        "UPDATE pongdang_data.attachment_collection SET next_attempt_at=NULL "
        "WHERE state<>'failed'"
    )
