import csv,pathlib,json
b=pathlib.Path('docs/research/water-travel-index')
p=b/'working/sw_evidence.csv'
rows=list(csv.DictReader(p.open()));fields=list(rows[0])
rows=[r for r in rows if r['evidence_id'] not in ['SW12','SW13']]
def add(**d):rows.append({k:d.get(k,'NR') for k in fields})
common=dict(source_type='official_guidance',authors='Centers for Disease Control and Prevention (CDC)',year='2025',design='미국공중보건 공식이용지침; 효과실험아님',country_climate='미국; 시설hot tub/spa',season='연중',activity='onsen 후보 중 hot tub/spa 입욕',outcome_domain='C',sample_size='해당없음; 연구표본아님',korea_directness='해외공식간접; 한국법령/현장운영조건 별도확인',access_status='full_text_checked',evidence_strength='정책 권위/효과 근거 아님',strength_rationale='현재접근가능CDC원지침; 선호의효과크기연구아님')
add(**common,evidence_id='SW12',study_id='SW-S10',sample_family='CDC_HOT_TUB_HEALTH_GUIDANCE_2025_05_20',title='What You Can Do to Stay Healthy in Hot Tubs',url='https://www.cdc.gov/healthy-swimming/safety/what-you-can-do-to-stay-healthy-in-hot-tubs.html',population='hot tub 이용자;5세미만사용금지·임신부사용전의료진상담',comparison='hot tub 수온40°C초과 여부',input_definition_unit_aggregation='시설욕조수온°C/°F; 평균시간창NR; 이용시확인',outcome_measure='건강·상해예방을위한운영/이용상한안내',finding_effect_uncertainty='물은104°F(40°C)보다높지않아야함.5세미만은hot tub사용금지.임신부는사용전상담.효과크기/CI없음',condition_range='hot tub/spa; 시간·개인별안전확률 또는 일반해수수영상한 아님',location_in_source='2025-05-20; Follow rules for healthy and safe use; Observe the hot tub and its surroundings',confounders_bias='지침제시만으로임계값의실험적최적성확인불가',applicability_limits='40°C이하도무조건안전/선호상위아님; 고령자별열임계값미제시; 한국모든온천에법적의무로확대불가',code_implication='legacy >40°C STOP은hot tub에한정한공식상한정책근거로수정유지가능; 해수수영공통상한으로쓰지않음;연령/임신주의별도',conversion_note='104°F와40°C는CDC병기값; 자체변환없음; >40과≥40혼동금지',search_ids='sw-q13;sw-o26')
add(**common,evidence_id='SW13',study_id='SW-S11',sample_family='CDC_HOT_TUB_LEGIONELLA_GUIDANCE_2025_05_28',title='About Protecting Yourself from Legionella in Hot Tubs',url='https://www.cdc.gov/healthy-swimming/prevention/preventing-legionella-from-hot-tubs.html',population='50세이상·현재/과거흡연자·만성폐질환·면역저하자',comparison='Legionnaires disease 취약군',input_definition_unit_aggregation='레지오넬라오염욕조에어로졸흡입; 연령≥50년;노출시간NR',outcome_measure='Legionnaires disease 감염위험안내',finding_effect_uncertainty='50세이상등을더취약한집단으로명시; 개인위험계수/수온별효과/CI없음',condition_range='hot tub 미스트의세균감염위험; 열적쾌적성/고령자열상한연구아님',location_in_source='2025-05-28; Exposure; Risk factors; Prevention steps and strategies',confounders_bias='위험안내; 직접조사결과/정량효과아님',applicability_limits='고령위험을나이별온도감점계수로전환불가; 열관리만으로감염관리대체불가',code_implication='장비/시설소독·수질·취약군안내분리;40°C상한충족을전체안전으로표시하지않음',conversion_note='원문연령50years이상그대로;65세로치환안함',search_ids='sw-q13;sw-o29')
with p.open('w',newline='') as f:w=csv.DictWriter(f,fieldnames=fields);w.writeheader();w.writerows(rows)
print('evidence',len(rows),'sources',len({r['study_id'] for r in rows}))

