"""Explicit, additive initialization of Pongdang's own collection schema."""

import argparse
from contextlib import contextmanager

import psycopg
from psycopg import sql

from app.config import Settings
from app.data_reader import CATALOG

SCHEMA = "pongdang_data"
VERSION = 1
TYPES = {
    "text": "text",
    "number": "double precision",
    "boolean": "boolean",
    "json": "jsonb",
    "datetime": "timestamptz",
    "date": "date",
}


@contextmanager
def connect(settings: Settings):
    if settings.postgres_host.lower() == "cksdb":
        raise ValueError("The shared legacy database is not a Pongdang write target")
    if settings.postgres_db not in {"pongdang", "pongdang_test"}:
        raise ValueError("Unexpected Pongdang database")
    with psycopg.connect(
        host=settings.postgres_host,
        port=settings.postgres_port,
        dbname=settings.postgres_db,
        user=settings.postgres_user,
        password=settings.postgres_password.get_secret_value(),
        connect_timeout=3,
        options="-c statement_timeout=10000 -c lock_timeout=3000",
    ) as connection:
        if connection.info.server_version < 180000:
            raise ValueError("Pongdang writes require its PostgreSQL 18 database")
        yield connection


def initialize(settings: Settings) -> bool:
    with connect(settings) as connection:
        connection.execute("SELECT pg_advisory_xact_lock(hashtext('pongdang-schema'))")
        if connection.execute("SELECT to_regnamespace('pongdang_data')").fetchone()[0]:
            # Never adopt an unknown schema or overwrite existing tables/data.
            row = connection.execute(
                "SELECT version FROM pongdang_data.schema_version WHERE id=1"
            ).fetchone()
            if row != (VERSION,):
                raise ValueError("Unrecognized Pongdang schema version")
            return False
        connection.execute("CREATE SCHEMA pongdang_data")
        connection.execute("REVOKE ALL ON SCHEMA pongdang_data FROM PUBLIC")
        for dataset in CATALOG:
            columns = []
            for column in dataset["columns"]:
                name = column["key"]
                kind = (
                    "bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
                    if name == "id"
                    else "bigint"
                    if name.endswith("_id") and column["type"] == "number"
                    else TYPES[column["type"]]
                )
                columns.append(
                    sql.SQL("{} {}").format(sql.Identifier(name), sql.SQL(kind))
                )
            connection.execute(
                sql.SQL("CREATE TABLE {} ({})").format(
                    sql.Identifier(SCHEMA, dataset["table"]), sql.SQL(",").join(columns)
                )
            )
        connection.execute(
            "ALTER TABLE pongdang_data.conditions_observationsnapshot "
            "ADD FOREIGN KEY (spot_id) REFERENCES pongdang_data.spots_waterspot(id), "
            "ADD UNIQUE (provider,provider_record_id,spot_id)"
        )
        connection.execute(
            "ALTER TABLE pongdang_data.conditions_observationmetric "
            "ADD FOREIGN KEY (snapshot_id) "
            "REFERENCES pongdang_data.conditions_observationsnapshot(id), "
            "ADD UNIQUE (snapshot_id,name)"
        )
        connection.execute(
            "CREATE TABLE pongdang_data.ingestion_batches ("
            "provider text NOT NULL, batch_key text NOT NULL, digest text NOT NULL, "
            "created_at timestamptz NOT NULL DEFAULT now(), "
            "PRIMARY KEY(provider,batch_key))"
        )
        connection.execute(
            "CREATE TABLE pongdang_data.schema_version "
            "(id integer PRIMARY KEY CHECK(id=1), version integer NOT NULL)"
        )
        connection.execute(
            "INSERT INTO pongdang_data.schema_version VALUES (1,%s)", [VERSION]
        )
    return True


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--initialize", action="store_true", required=True)
    parser.parse_args()
    try:
        created = initialize(Settings())
    except Exception:
        raise SystemExit(
            "Pongdang schema initialization failed; no partial changes committed"
        ) from None
    print(
        "Pongdang schema initialized"
        if created
        else "Pongdang schema already initialized"
    )


if __name__ == "__main__":
    main()
