// Display-only dictionaries, scoped by dataset and field. Never rewrite DB values.
const metrics: Record<string, string> = {
  air_temperature_c: "기온",
  relative_humidity_pct: "상대 습도",
  precipitation_1h_mm: "1시간 강수량",
  wind_speed_ms: "풍속",
  wind_direction_degrees: "풍향",
  cloud_cover_pct: "구름 덮임 비율",
  precipitation_probability_pct: "강수 확률",
  minimum_air_temperature_c: "최저 기온",
  maximum_air_temperature_c: "최고 기온",
  water_temperature_c: "수온",
  wave_height_m: "파고",
  wave_period_seconds: "파주기",
  tidal_height_cm: "조위",
  current_speed_ms: "유속",
  rip_current_risk: "이안류 위험 지표",
  beach_activity_index: "해수욕 활동 지수",
  surf_activity_index: "서핑 활동 지수",
  water_ph: "수소 이온 농도 (pH)",
  turbidity_ntu: "탁도",
  dissolved_oxygen_mg_l: "용존 산소량",
  river_discharge_m3s: "하천 유량",
  hot_tub_temperature_c: "온천탕 수온",
  dew_point_c: "이슬점 온도",
  air_temperature: "기온",
  relative_humidity: "상대 습도",
  precipitation: "강수량",
  wind_speed: "풍속",
  wind_direction: "풍향",
  water_temperature: "수온",
  tide_level: "조위",
  current_speed: "유속",
  current_direction: "유향",
  sulfur_dioxide: "아황산가스 농도",
  carbon_monoxide: "일산화탄소 농도",
  ozone: "오존 농도",
  nitrogen_dioxide: "이산화질소 농도",
  pm10: "미세먼지 (PM10)",
  pm25: "초미세먼지 (PM2.5)",
  pm10_24h_predicted_moving: "미세먼지 24시간 예측 이동 농도",
  pm25_24h_predicted_moving: "초미세먼지 24시간 예측 이동 농도",
  airkorea_comprehensive_index: "에어코리아 통합대기환경지수",
  airkorea_comprehensive_grade: "에어코리아 통합대기환경 등급",
  airkorea_so2_grade: "에어코리아 아황산가스 등급",
  airkorea_co_grade: "에어코리아 일산화탄소 등급",
  airkorea_o3_grade: "에어코리아 오존 등급",
  airkorea_no2_grade: "에어코리아 이산화질소 등급",
  airkorea_pm10_24h_grade: "에어코리아 미세먼지 24시간 등급",
  airkorea_pm25_24h_grade: "에어코리아 초미세먼지 24시간 등급",
  airkorea_pm10_1h_grade: "에어코리아 미세먼지 1시간 등급",
  airkorea_pm25_1h_grade: "에어코리아 초미세먼지 1시간 등급",
  airkorea_measurement_network: "에어코리아 측정망 종류",
  sunrise: "일출",
  solar_transit: "태양 남중",
  sunset: "일몰",
  moonrise: "월출",
  lunar_transit: "달 남중",
  moonset: "월몰",
  civil_dawn: "시민박명 시작",
  civil_dusk: "시민박명 종료",
  nautical_dawn: "항해박명 시작",
  nautical_dusk: "항해박명 종료",
  astronomical_dawn: "천문박명 시작",
  astronomical_dusk: "천문박명 종료",
  uv_index: "자외선 지수",
  electrical_conductivity: "전기전도도",
  ph: "수소 이온 농도 (pH)",
  dissolved_oxygen: "용존 산소량",
  turbidity: "탁도",
  temporary_turbidity: "임시 탁도",
  wiper: "와이퍼 상태",
  solar_radiation: "일사량",
  voltage: "전압",
  water_level_1: "수위 1",
  water_level_2: "수위 2",
  salinity: "염분",
  chlorophyll_a: "클로로필 a",
  chemical_oxygen_demand: "화학적 산소 요구량",
  total_nitrogen: "총질소",
  total_phosphorus: "총인",
  ammonium_nitrogen: "암모늄성 질소",
  nitrate_nitrogen: "질산성 질소",
  cyanobacteria: "남조류",
  phosphate_phosphorus: "인산염 인",
  daily_visitors: "지역별 일 방문자 수",
  visitor_category_code: "방문자 유형 코드",
  visitor_category_name: "방문자 유형명",
  day_of_week_code: "요일 코드",
  day_of_week_name: "요일명",
  // Normalized names emitted by weather.py, marine.py and water.py.
  minimum_air_temperature: "최저 기온",
  maximum_air_temperature: "최고 기온",
  precipitation_probability: "강수 확률",
  precipitation_type: "강수 형태 코드",
  sky_condition: "하늘 상태 코드",
  eastward_wind: "동서 바람 성분 (동쪽 양수)",
  northward_wind: "남북 바람 성분 (북쪽 양수)",
  snowfall: "적설량",
  lightning: "낙뢰 코드",
  gust_direction: "돌풍 풍향",
  gust_speed: "돌풍 풍속",
  wind_direction_10min: "10분 평균 풍향",
  wind_speed_10min: "10분 평균 풍속",
  precipitation_detection: "강수 감지 코드",
  precipitation_15min: "15분 강수량",
  precipitation_12h: "12시간 강수량",
  precipitation_day: "일 강수량",
  station_pressure: "현지 기압",
  sea_level_pressure: "해면 기압",
  dew_point: "이슬점 온도",
  wind_direction_sensor2: "두 번째 센서 풍향",
  wind_speed_sensor2: "두 번째 센서 풍속",
  gust_speed_sensor2: "두 번째 센서 돌풍 풍속",
  wind_gust: "순간 최대 풍속",
  air_pressure: "기압",
  wave_height: "파고",
  wave_period: "파주기",
  wave_direction: "파향",
  maximum_wave_height: "최대 파고",
  maximum_wave_period: "최대 파주기",
  average_wave_height: "평균 파고",
  maximum_wind_speed: "최대 풍속",
  minimum_wind_speed: "최소 풍속",
  official_rip_index: "기관 이안류 지수",
  official_rip_message: "기관 이안류 안내",
  official_activity_index: "기관 활동예보 지수",
  official_activity_grade: "기관 활동예보 등급",
  tide_extremum_code: "고조·저조 구분 코드",
  surfing_skill: "서핑 숙련도 구분",
  opening_status: "개장 상태",
  weather: "기상 상태",
  forecast_half_day: "예보 오전·오후 구분",
  experience_start: "갯벌 체험 시작 시각",
  experience_end: "갯벌 체험 종료 시각",
  nitrite_nitrogen: "아질산성 질소",
  dissolved_inorganic_nitrogen: "용존 무기 질소",
  dissolved_inorganic_phosphorus: "용존 무기 인",
  silicate_silicon: "규산 규소",
  suspended_solids: "부유 물질",
  biochemical_oxygen_demand: "생물화학적 산소 요구량",
  total_coliform: "총대장균군",
  e_coli: "대장균 지표 (ITEM_ECOLI)",
  total_organic_carbon: "총유기탄소",
  sample_depth: "채수 수심",
  river_level: "하천 수위",
  river_flow: "하천 유량",
  ammonia_nitrogen: "암모니아성 질소",
  water_layer: "수질 측정층",
  observation_precision: "관측 시각 정밀도",
  unit_metadata: "제공처 단위 정보",
  official_wqi_index: "기관 해양수질평가 지수",
  official_wqi_grade: "기관 해양수질평가 등급",
  sample_round: "채수 회차",
  // weather._mid splits a bounded 10,000-character bulletin into 500-character parts.
  ...Object.fromEntries(Array.from({ length: 20 }, (_, i) => [
    `weather_outlook_part_${i + 1}`, `중기 기상 전망 (${i + 1}번째 부분)`,
  ])),
};
const newCollectionProviders: Record<string, string> = {
  khoa_tide_timeseries: "국립해양조사원 조석 시계열 예보",
  khoa_hf_current: "국립해양조사원 HF 해수유동 실측",
  khoa_current_timeseries: "국립해양조사원 조류 시계열 예보",
  khoa_roms: "국립해양조사원 ROMS 표층 예측",
  koem_wemo_catalog: "해양환경공단 특별관리해역 자동수질 정점 목록",
  koem_wemo_water_quality: "해양환경공단 특별관리해역 자동수질 관측",
  tourapi_english: "한국관광공사 영문 관광정보",
  tourapi_japanese: "한국관광공사 일문 관광정보",
  tourapi_chinese_simplified: "한국관광공사 중문 간체 관광정보",
  tourapi_chinese_traditional: "한국관광공사 중문 번체 관광정보",
  tourapi_daily_visitors: "한국관광공사 지역별 일 방문통계",
};
const providers: Record<string, string> = {
  ...newCollectionProviders,
  kma_nowcast: "기상청 초단기 실황",
  kma_ultra_forecast: "기상청 초단기 예보",
  kma_short_forecast: "기상청 단기 예보",
  kma_mid_forecast: "기상청 중기 예보",
  kma_warnings: "기상청 특보 발표 자료",
  kma_aws: "기상청 AWS 관측",
  kma_buoy: "기상청 해양 부이 관측",
  khoa_beach: "국립해양조사원 해수욕 예보",
  khoa_surfing: "국립해양조사원 서핑 예보",
  khoa_mudflat: "국립해양조사원 갯벌 체험 예보",
  khoa_rip_current: "국립해양조사원 이안류 지표",
  khoa_tide_recent: "국립해양조사원 조위 관측소 최신 자료",
  khoa_buoy_recent: "국립해양조사원 해양 관측 부이 최신 자료",
  khoa_water_temperature: "국립해양조사원 수온 관측",
  khoa_tide_level: "국립해양조사원 조위 관측",
  khoa_tide_extrema: "국립해양조사원 고조·저조 예측",
  khoa_waves: "국립해양조사원 파랑 예측",
  koem_catalog: "해양환경공단 관측 지점 목록",
  koem_water_quality: "해양환경공단 해양 수질",
  nier_water_quality: "국립환경과학원 수질 측정 자료",
  hrfco_waterlevel: "홍수통제소 하천 수위",
  KAKAO_LOCAL: "카카오 주변 장소·시설 정보",
  TOURAPI_KOREAN: "한국관광공사 국문 관광정보",
  AIRKOREA: "에어코리아 대기환경·측정소",
  KASI_RISE_SET: "한국천문연구원 출몰시각",
  KMA_FORECAST_ZONE: "기상청 예보구역",
  KMA_UV: "기상청 자외선 예보",
  KMA: "기상청",
  KHOA: "국립해양조사원",
  TourAPI: "한국관광공사 관광 정보",
  Valhalla: "이동 경로 API",
  PONGDANG_FUSION: "내부 근거 통합",
};
const activities: Record<string, string> = {
  swim: "수영", rafting: "래프팅", onsen: "온천", mudflat: "갯벌 체험",
  relax: "휴식", surf: "서핑",
};
const tasks: Record<string, string> = {
  ...newCollectionProviders,
  airkorea_stations: "에어코리아 측정소 목록",
  airkorea_observations: "에어코리아 대기오염 관측",
  kasi_rise_set: "한국천문연구원 출몰시각",
  kma_forecast_zones: "기상청 예보구역 목록",
  kma_uv_forecast: "기상청 자외선 예보",
  kwater_dam_release: "한국수자원공사 수문 방류정보",
  kma_nowcast: "기상청 초단기 실황",
  kma_ultra_forecast: "기상청 초단기 예보",
  kma_short_forecast: "기상청 단기 예보",
  kma_mid_forecast: "기상청 중기 예보",
  kma_warnings: "기상청 특보 발표 자료",
  kma_aws: "기상청 AWS 관측",
  kma_buoy: "기상청 해양 부이 관측",
  khoa_beach: "국립해양조사원 해수욕 예보",
  khoa_surfing: "국립해양조사원 서핑 예보",
  khoa_mudflat: "국립해양조사원 갯벌 체험 예보",
  khoa_rip_current: "국립해양조사원 이안류 지표",
  khoa_tide_recent: "국립해양조사원 조위 관측소 최신 자료",
  khoa_buoy_recent: "국립해양조사원 해양 관측 부이 최신 자료",
  khoa_water_temperature: "국립해양조사원 수온 관측",
  khoa_tide_level: "국립해양조사원 조위 관측",
  khoa_tide_extrema: "국립해양조사원 고조·저조 예측",
  khoa_waves: "국립해양조사원 파랑 예측",
  koem_catalog: "해양환경공단 관측 지점 목록",
  koem_water_quality: "해양환경공단 해양 수질",
  nier_water_quality: "국립환경과학원 수질 측정 자료",
  hrfco_waterlevel: "홍수통제소 하천 수위",
  kakao_places: "카카오 주변 장소·시설 목록",
  tourism_places: "한국관광공사 주변 관광지 목록",
  forecast_projection: "수집 근거 기반 예보 조회 자료 갱신",
  water_index_evaluation: "활동별 조건 지수 평가",
  livecam_checks: "공식 카메라 접속 상태 확인",
  condition_notifications: "구독 조건 확인·알림 처리",
  quality_comparison: "예보·관측 품질 비교",
  "weather-nowcast": "현재 기상 수집",
  "weather-short-forecast": "단기 기상 예보 수집",
  marine: "해양 관측 수집",
  "marine-activity-forecast": "해양 활동 예보 수집",
  "derive-suitability": "원본 근거로 파생 지표 계산",
  "water-index-general": "일반 참여자 적합도 평가",
  "water-index-family": "가족 참여자 적합도 평가",
  "condition-retention": "보존 정책에 따른 이력 정리",
  "daily-forecast": "일별 예보 계산",
  "route-matrix-drive": "자동차 이동 경로 행렬",
  "route-matrix-walk": "도보 이동 경로 행렬",
  "route-matrix-bicycle": "자전거 이동 경로 행렬",
};
const collectionStates: Record<string, string> = {
  pending: "실행 대기",
  running: "실행 중",
  succeeded: "수집 완료",
  partial: "일부 수집 (조회 범위 제한)",
  no_data: "정상 응답 · 대상 자료 없음",
  disabled: "비활성화",
  failed: "수집 실패",
  skipped: "건너뜀",
};
const evidenceStates: Record<string, string> = {
  recorded: "수집 기록",
  stale: "유효 기간 경과",
  superseded: "이전 수정본 (이력 보존)",
  missing: "원본 값 없음",
};
const collectionCodes: Record<string, string> = {
  KEY_NOT_CONFIGURED: "서버에 필요한 API 키가 설정되지 않음",
  APPROVAL_PENDING: "제공처 서비스 심의·승인 대기",
  SERVICE_APPROVAL_UNCONFIRMED: "해당 서비스 승인·인증 성공 확인 필요",
  ADAPTER_PENDING: "자동 수집 연결 구현 대기",
  BOUNDED_CATALOG: "조회 상한이 있는 목록 수집 · 전체 목록을 뜻하지 않음",
  COLLECTION_ERROR: "수집·검증·저장 처리 실패",
  SOURCE_SCOPE_TOO_LARGE: "처리 대상 자료가 작업당 조회 상한 (5,000건)을 초과함",
  NETWORK_ERROR: "제공처 네트워크 요청 실패",
  SERVICE_NOT_AUTHORIZED: "제공처 인증·서비스 활용 신청 상태 확인 필요",
  PROVIDER_20: "제공처 활용 신청·승인 상태 확인 필요",
  PROVIDER_30: "키와 해당 서비스 활용 신청 상태 확인 필요",
  HTTP_401: "제공처 인증 거부 (HTTP 401)",
  HTTP_403: "제공처 접근 거부 (HTTP 403)",
  HTTP_429: "제공처 요청 한도 초과 (HTTP 429)",
  REQUEST_BUDGET_EXCEEDED: "한 번의 수집 요청 상한 초과",
  // These are adapter/worker validation outcomes, not provider status meanings.
  MISSING_CREDENTIAL: "서버의 제공처 인증키가 비어 있음",
  ENDPOINT_NOT_ALLOWED: "승인된 HTTPS 제공처 주소가 아님",
  RESPONSE_TOO_LARGE: "제공처 응답 크기가 수집 상한을 초과함",
  UNEXPECTED_HTML: "데이터 대신 HTML 문서가 반환됨",
  INVALID_XML: "제공처 XML 응답 해석 실패",
  INVALID_JSON: "제공처 JSON 응답 해석 실패",
  INVALID_JSON_STRUCTURE: "제공처 JSON 최상위 구조가 예상과 다름",
  PROVIDER_ERROR: "제공처가 오류 응답을 반환함",
  PROVIDER_MISSING_STATUS: "제공처 응답의 처리 결과 코드가 없음",
  PROVIDER_10: "제공처 오류 응답 (코드 10 · 해당 서비스 명세 확인 필요)",
  HTTP_500: "제공처 내부 서버 오류 (HTTP 500)",
  HTTP_502: "제공처 게이트웨이 오류 (HTTP 502)",
  HTTP_503: "제공처 일시 이용 불가 (HTTP 503)",
  HTTP_504: "제공처 게이트웨이 응답 시간 초과 (HTTP 504)",
  INVALID_RESPONSE: "제공처 응답 구조가 예상과 다름",
  INVALID_RESPONSE_BODY: "제공처 응답 본문 구조가 예상과 다름",
  INVALID_RESPONSE_ITEMS: "제공처 응답 항목 구조가 예상과 다름",
  INVALID_RESPONSE_ROOT: "제공처 응답의 최상위 항목이 예상과 다름",
  INVALID_TOTAL_COUNT: "제공처 전체 건수가 누락되거나 실제 응답과 맞지 않음",
  CONFLICTING_PROVIDER_RECORD: "같은 제공처 기록 ID에 서로 다른 값이 반환됨",
  RECORD_LIMIT_EXCEEDED: "수집 기록 수가 한 번의 처리 상한을 초과함",
  UNSUPPORTED_SERVICE: "구현된 수집 서비스에 없는 요청",
  INCOMPLETE_PAGINATION: "전체 건수에 도달하기 전에 응답 페이지가 끊김",
  MISSING_STATION_NAME: "제공처 관측 지점 이름이 없음",
  MISSING_SOURCE_TIME: "제공처 관측·예측 시각이 없음",
  INVALID_SOURCE_TIME: "제공처 날짜·시각을 해석할 수 없음",
  MISSING_STATION_ID: "제공처 관측 지점 식별자가 없음",
  CONFLICTING_STATION: "같은 관측 지점 ID에 서로 다른 지점 정보가 반환됨",
  FUTURE_OBSERVATION: "관측 시각이 실제 수집 시각보다 미래임",
  INVALID_NIER_RESPONSE: "국립환경과학원 응답 구조가 예상과 다름",
  INVALID_LAB_RESPONSE: "수질 측정 응답 구조가 예상과 다름",
  INVALID_NIER_ITEMS: "수질 측정 응답 항목 구조가 예상과 다름",
  MISSING_OR_INVALID_COORDINATE: "관측·예보 좌표가 없거나 허용 범위를 벗어남",
  PAGE_LIMIT_EXCEEDED: "제공처 한 페이지 건수가 요청 상한을 초과함",
  UNSTABLE_PAGINATION: "페이지를 읽는 동안 제공처 전체 건수가 바뀜",
  REPEATED_PAGE: "제공처가 동일한 페이지를 반복 반환함",
  UNEXPECTED_TARGET_DATE: "예측 대상 날짜가 요청 날짜와 다름",
  INCOMPLETE_SNAPSHOT: "조회한 최신 시각의 관측 자료가 이어서 반환되지 않음",
  UNEXPECTED_OBSERVATION_TIME: "같은 관측 묶음에 다른 시각의 기록이 포함됨",
  OUTSIDE_REQUESTED_GRID: "예보 격자가 요청한 좌표 범위를 벗어남",
  INVALID_SOURCE_VALUE: "제공처 값의 자료형·길이가 허용 형식과 다름",
  MISSING_SOURCE_IDENTITY: "제공처 기록 식별에 필요한 값이 없음",
  INVALID_AIR_STATION_SCOPE: "설정된 대기 측정소 조회 범위가 유효하지 않음",
  INCONSISTENT_SOURCE_COUNT: "제공처 전체 건수가 응답 자료와 맞지 않음",
  SOURCE_ERROR: "제공처가 정상 처리 이외의 결과 코드를 반환함",
  INVALID_SOURCE_COUNT: "제공처 전체 건수를 해석할 수 없음",
  INVALID_SOURCE_ITEMS: "제공처 자료 목록의 항목 형식이 예상과 다름",
  INCOMPLETE_SOURCE_PAGE: "요청 범위의 제공처 자료가 페이지에서 누락됨",
  SOURCE_PAGE_LIMIT: "제공처 응답이 한 번의 페이지 조회 상한을 초과함",
  INVALID_SOURCE_STRUCTURE: "제공처 자료 구조에 필요한 항목이 없음",
  INVALID_SOURCE_NUMBER: "제공처 측정값을 유효한 숫자로 해석할 수 없음",
  INVALID_SOURCE_COORDINATE: "제공처 좌표를 유효한 위도·경도로 해석할 수 없음",
  AMBIGUOUS_AIR_STATION: "동일 이름의 대기 측정소가 여러 개여서 식별할 수 없음",
  AIR_STATION_NOT_FOUND: "설정된 대기 측정소를 제공처 목록에서 찾을 수 없음",
  SOURCE_SCOPE_MISMATCH: "제공처 자료의 지점·지역이 요청 범위와 다름",
  INCOMPLETE_AIR_OBSERVATION: "대기 관측 응답에 측정 농도 항목이 없음",
  INVALID_FORECAST_ZONE_SCOPE: "설정된 예보구역 조회 범위가 유효하지 않음",
  INVALID_ASTRONOMY_EVENT: "출몰시각 값을 유효한 시각으로 해석할 수 없음",
  INVALID_ASTRONOMY_SCOPE: "설정된 출몰시각 조회 지역이 유효하지 않음",
  INCOMPLETE_ASTRONOMY_EVENTS: "출몰시각 응답에 필요한 사건 항목이 없음",
  INVALID_UV_AREA_SCOPE: "설정된 자외선 예보 지역이 유효하지 않음",
  INCOMPLETE_UV_FORECAST: "자외선 응답에 필요한 예보 항목이 없음",
  CONFLICTING_FIELD_ALIAS: "같은 항목으로 정규화되는 제공처 필드 값이 서로 다름",
  PAGINATION_TOTAL_CHANGED: "페이지를 읽는 동안 제공처 전체 건수가 바뀜",
  PAGINATION_REPEATED_RECORD: "제공처 페이지에 동일 기록이 반복 반환됨",
  INCOMPLETE_STATION_CATALOG: "관측 지점 목록이 전체 건수보다 적음",
  CONFIGURED_STATION_NOT_FOUND: "설정된 관측 지점을 제공처 목록에서 찾을 수 없음",
  UNEXPECTED_STATION: "응답 관측 지점이 요청 지점과 다름",
  UNEXPECTED_OBSERVATION_DATE: "응답 관측 날짜가 요청 날짜와 다름",
  MISSING_MEASUREMENT_FIELDS: "제공처 응답에 수집할 측정 항목이 없음",
  UNSUPPORTED_LANGUAGE: "구현된 관광정보 언어에 없는 요청",
  CONFLICTING_PLACE: "같은 장소 ID에 서로 다른 장소 정보가 반환됨",
  FUTURE_SOURCE_MODIFICATION: "제공처 자료 수정 시각이 수집 시각보다 미래임",
  INVALID_SOURCE_CHRONOLOGY: "제공처 자료 수정 시각이 생성 시각보다 이전임",
  INVALID_VISITOR_COUNT: "방문자 수를 유효한 음이 아닌 숫자로 해석할 수 없음",
  INVALID_PLACE_RESPONSE: "장소 검색 응답 구조가 예상과 다름",
  INVALID_PLACE_RECORD: "장소 검색 기록에 필요한 항목이 없음",
  INVALID_TOURISM_RESPONSE: "관광정보 응답 구조가 예상과 다름",
  INCONSISTENT_PAGINATION: "제공처 페이지 건수·종료 상태가 서로 맞지 않음",
  PAGINATION_LIMIT: "요청 자료가 한 번의 페이지 조회 상한을 초과함",
  DUPLICATE_SOURCE_METRIC: "같은 시점의 동일 측정 항목이 중복 반환됨",
  INVALID_MID_FORECAST: "중기 전망 본문이 없거나 허용 길이를 초과함",
  INCOMPLETE_HUB_RESPONSE: "기상청 API 허브 응답이 불완전함 (시작·종료 표식 누락)",
  AMBIGUOUS_HUB_COLUMNS: "기상청 API 허브 열 이름이 중복되거나 모호함",
  INVALID_HUB_COLUMNS: "기상청 API 허브 열 구조가 예상과 다름",
  INVALID_HUB_ROW: "기상청 API 허브 기록의 시각 형식이 예상과 다름",
  HUB_ROW_LIMIT: "기상청 API 허브 기록이 처리 상한을 초과함",
  MISSING_HUB_HEADER: "기상청 API 허브 응답에 열 이름 헤더가 없음",
  INVALID_STATION_CONFIGURATION: "설정된 기상 관측소 코드 형식이 유효하지 않음",
  UNEXPECTED_HUB_STATION: "기상청 API 허브 응답 관측소가 요청과 다름",
  MISSING_HUB_METRICS: "기상청 API 허브 응답에 수집할 측정 항목이 없음",
  CAMERA_CHECK_FAILED: "공식 카메라 접속 확인에 실패한 항목이 있음",
  NOTIFICATION_DELIVERY_UNCONFIRMED: "일부 알림의 발송 결과가 확인되지 않음",
  NOTIFICATION_DELIVERY_NOT_CONFIGURED: "일부 알림의 발송 서비스 설정이 없음",
};
const dictionaries: Record<string, Record<string, string>> = {
  "runs.task_name": tasks,
  "runs.status": collectionStates,
  "runs.error_code": collectionCodes,
  "collection-jobs.task_name": tasks,
  "collection-jobs.state": collectionStates,
  "collection-jobs.last_error": collectionCodes,
  "metrics.state": evidenceStates,
  "snapshots.state": evidenceStates,
  "metrics.name": metrics,
  "metrics.unit": {
    degC: "섭씨 (°C)", percent: "백분율 (%)", mm: "밀리미터",
    "°C": "섭씨 (°C)", "cm/s": "초당 센티미터", "16-point": "16방위",
    "ug/m3": "세제곱미터당 마이크로그램", ppm: "백만분율",
    KST: "한국 표준시", index: "지수", code: "구분 코드", "명/일": "하루 방문자 수",
    "m/s": "초당 미터", degree: "각도 (°)", m: "미터", s: "초",
    cm: "센티미터",
    pH: "산성·염기성 척도", NTU: "탁도 단위", "mg/L": "리터당 밀리그램",
    "m3/s": "초당 세제곱미터", "m³/s": "초당 세제곱미터",
    "%": "백분율 (%)", hPa: "헥토파스칼", psu: "실용 염분 단위",
    "mm/1h": "1시간 강수량 (mm)", "cm/1h": "1시간 적설량 (cm)",
    "mm/15min": "15분 강수량 (mm)", "mm/12h": "12시간 강수량 (mm)",
    "mm/day": "일 강수량 (mm)", 명: "사람 수 (명)",
  },
  "metrics.mode": { observation: "관측", observed: "관측", forecast: "예보", derived: "파생 계산" },
  "metrics.source": providers,
  "snapshots.provider": providers,
  "source-stations.provider": providers,
  "source-places.provider": providers,
  "spots.catalog_source": providers,
  "route-snapshots.provider": providers,
  "route-snapshots.transport": { drive: "자동차", walk: "도보", bicycle: "자전거" },
  "spots.type": {
    beach: "해변", valley: "계곡", onsen: "온천", mudflat: "갯벌",
    tourism: "관광정보 장소", facility: "주변 시설 검색 결과",
    beach_search_result: "해수욕장 검색 결과",
    weather_forecast_grid: "기상 예보 격자", weather_forecast_zone: "기상 예보구역",
    weather_station: "기상 관측소", region: "광역 예보 지역",
    marine_buoy: "해양 기상 부이", buoy_recent: "해양 관측 부이",
    tide_station: "조위 관측소", surfing: "서핑 예보 지점",
    rip_current: "이안류 관측 지점", waves: "파랑 예측 지점",
    hf_current_grid: "HF 해수유동 관측 격자", marine_model_grid: "해양 수치모델 격자",
    tidal_current_forecast_point: "조류 시계열 예보 지점",
    marine_water_quality: "해양 수질 측정 정점",
    marine_automated_water_quality: "해양 자동수질 측정 정점",
    river_water_quality: "하천 수질 측정 지점", river_level: "하천 수위 관측소",
    air_quality_station: "대기오염 측정소", astronomy_location: "출몰시각 조회 지역",
    uv_forecast_area: "자외선 예보 지역",
    tourism_administrative_statistics: "관광 방문통계 행정구역",
  },
  "facilities.type": { parking: "주차장", toilet: "화장실", shower: "샤워실", convenience: "편의점" },
  "scores.activity": activities,
  "forecasts.activity": activities,
  "scores.participant_profile": { general: "일반 참여자", family: "가족 참여자" },
  "forecasts.participant_profile": { general: "일반 참여자", family: "가족 참여자" },
};

export function isCodeField(dataset: string, field: string): boolean {
  return Object.hasOwn(dictionaries, `${dataset}.${field}`);
}

export function codeName(dataset: string, field: string, value: string): string | undefined {
  if (!isCodeField(dataset, field) || value === "") return undefined;
  const dictionary = dictionaries[`${dataset}.${field}`];
  return Object.hasOwn(dictionary, value) ? dictionary[value] : "미등록 코드";
}

// A generic category label does not establish a provider-specific code meaning.
const errorCodesNeedingReview = new Set(["PROVIDER_10"]);

export function codeNeedsReview(dataset: string, field: string, value: string): boolean {
  const label = codeName(dataset, field, value);
  if (label === undefined) return false;
  return label === "미등록 코드" || (
    ((dataset === "runs" && field === "error_code") ||
      (dataset === "collection-jobs" && field === "last_error")) &&
    errorCodesNeedingReview.has(value)
  );
}
