"""Explicit v11 storage for normalized place details and collection progress."""


def migrate_place_details(c):
    c.execute("""
        CREATE TABLE IF NOT EXISTS pongdang_data.place_detail (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          place_id bigint NOT NULL REFERENCES pongdang_data.collection_place(id),
          spot_id bigint REFERENCES pongdang_data.spots_waterspot(id),
          provider text NOT NULL,
          source_id text NOT NULL,
          content_type text NOT NULL,
          name text NOT NULL,
          evidence_hash text NOT NULL CHECK(evidence_hash ~ '^[0-9a-f]{64}$'),
          source_created_at timestamptz,
          source_modified_at timestamptz,
          catalog_modified_at timestamptz,
          availability text NOT NULL CHECK(availability IN ('available','empty')),
          opening_hours text,
          rest_days text,
          opening_period text,
          opening_date text,
          parking text,
          facilities text,
          contact text,
          homepage text,
          overview text,
          details jsonb NOT NULL CHECK(jsonb_typeof(details)='array'),
          photo_url text,
          photo_license text,
          fetched_at timestamptz NOT NULL,
          state text NOT NULL CHECK(state IN ('active','superseded')),
          UNIQUE(place_id,evidence_hash))
    """)
    c.execute("""
        CREATE UNIQUE INDEX IF NOT EXISTS place_detail_active_place
        ON pongdang_data.place_detail(place_id) WHERE state='active'
    """)
    c.execute("""
        CREATE INDEX IF NOT EXISTS place_detail_source
        ON pongdang_data.place_detail(provider,source_id)
    """)
    c.execute("""
        CREATE INDEX IF NOT EXISTS place_detail_spot
        ON pongdang_data.place_detail(spot_id)
    """)
    c.execute("""
        CREATE TABLE IF NOT EXISTS pongdang_data.place_detail_collection (
          id bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
          place_id bigint PRIMARY KEY REFERENCES pongdang_data.collection_place(id),
          state text NOT NULL CHECK(state IN
            ('available','empty','failed','unsupported')),
          catalog_modified_at timestamptz,
          content_type text NOT NULL,
          checked_at timestamptz NOT NULL,
          last_success_at timestamptz,
          next_attempt_at timestamptz,
          consecutive_failures integer NOT NULL DEFAULT 0
            CHECK(consecutive_failures>=0),
          error_code text NOT NULL DEFAULT '')
    """)
    c.execute("""
        CREATE INDEX IF NOT EXISTS place_detail_collection_due
        ON pongdang_data.place_detail_collection(next_attempt_at)
        WHERE next_attempt_at IS NOT NULL
    """)
    c.execute("""
        CREATE TABLE IF NOT EXISTS pongdang_data.place_detail_link (
          spot_id bigint PRIMARY KEY REFERENCES pongdang_data.spots_waterspot(id),
          place_id bigint NOT NULL REFERENCES pongdang_data.collection_place(id),
          match_method text NOT NULL CHECK(match_method IN
            ('provider_id','name_and_coordinates')),
          linked_at timestamptz NOT NULL)
    """)
    c.execute("""
        CREATE INDEX IF NOT EXISTS place_detail_link_place
        ON pongdang_data.place_detail_link(place_id)
    """)
    c.execute("""
        CREATE TABLE IF NOT EXISTS pongdang_data.place_detail_budget (
          service text NOT NULL,
          day date NOT NULL,
          calls integer NOT NULL CHECK(calls>=0),
          PRIMARY KEY(service,day))
    """)
    for table in (
        "place_detail",
        "place_detail_collection",
        "place_detail_link",
        "place_detail_budget",
    ):
        c.execute(f"REVOKE ALL ON pongdang_data.{table} FROM PUBLIC")
    from app.attachments.migrations import migrate_photo_detail_cache
    from app.ingestion.administrative import migrate_place_region_attempts

    migrate_photo_detail_cache(c)
    migrate_place_region_attempts(c)
    c.execute("UPDATE pongdang_data.schema_version SET version=11 WHERE id=1")
